@startuml

package Jugadores {
    !include jugador.puml
    !include rol.puml
    Jugador *-- Rol
}

!include moderador.puml

package Fases {
    !include fase_nocturna.puml
    !include fase_diurna.puml
}

title Diagrama de clases - Mafia

@enduml