!include estilos.puml
abstract class Eleccion {
    - votante : Jugador
    + Eleccion(Jugador votante)
    + {abstract} registrarEn(Conteo)
}

class Voto {
    - votado : Jugador
    + Voto(Jugador votante, Jugador votado)
    + registrarEn(Conteo)
}

class VotoEnBlanco {
    + VotoEnBlanco(Jugador)
    + registrarEn(Conteo)
}

Eleccion <|-- Voto
Eleccion <|-- VotoEnBlanco
