@startuml

!include estilos.puml
!include resultado_fase.puml
!include votacion_nocturna.puml

title Diagrama de clases - Fase Nocturna

package FaseNocturna {

    class FaseNocturna {
        - protegido : Jugador
        + laMafiaVotaA(Jugador mafioso, Jugador objetivo) : FaseNocturna
        + elMedicoProtegeA(Jugador objetivo) : FaseNocturna
        + ejecutar() : ResultadoNocturno
    }

    class ResultadoNocturno {
        - victimaElegida : Jugador
        - protegido : Jugador
        + huboEliminacion() : boolean
        + jugadorEliminado() : Jugador
    }

    ResultadoNocturno ..|> ResultadoFase
    FaseNocturna --> ResultadoNocturno
    FaseNocturna --> VotacionNocturna
}

@enduml
