!include estilos.puml
package Rol {
    abstract class Rol {
        + {abstract} bando() : Bando
        + bandoAparente() : Bando
        + conoceElRolDe(Jugador) : boolean
        + votoNocturno(Jugador votante, Jugador objetivo) : Eleccion
    }

    abstract class Bando {
        + {abstract} esMafia() : boolean
    }

    class Mafia {
        + esMafia() : boolean
    }

    class Ciudadanos {
        + esMafia() : boolean
    }

    class Mafioso {
        + conoceElRolDe(Jugador) : boolean
        + votoNocturno(Jugador votante, Jugador objetivo) : Voto
    }

    class Padrino {
        + bandoAparente() : Bando
    }

    class Sheriff {
    }

    class Detective {
    }

    class Medico {
    }

    class Ciudadano {}

    note bottom of Bando
        E3: gano(mafiososVivos, ciudadanosVivos)
        condicion de victoria polimorfica por bando
    end note

    note bottom of Detective
        E2: investigar(Jugador) usando
        bandoAparente() del investigado
    end note

    Rol <|- Ciudadano
    Rol <|-- Mafioso
    Rol <|-- Medico
    Rol <|--- Detective
    Rol <|-- Sheriff
    Mafioso <|-- Padrino

    Bando <|-- Mafia
    Bando <|-- Ciudadanos
    Rol ..> Bando
}
