!include estilos.puml
package VotacionDiurna {

    class VotacionDiurna {
        - votos : Collection<EleccionJugador>
        + jugadoresVotados() : Collection<Jugador>
        + votaciones() : Collection<EleccionJugador>
        + resultadoVotacion() : Voto
    }

    abstract class Eleccion {
        - votante : Jugador
        + Eleccion(Jugador votante)
    }

    class Voto {
        - votado : Jugador
        + Voto(Jugador votante, Jugador votado)
    }

    class VotoEnBlanco {
        + VotoEnBlanco(Jugador)
    }

    Eleccion <|-- Voto
    Eleccion <|-- VotoEnBlanco

    VotacionDiurna --> Eleccion
}