!include estilos.puml
!include eleccion.puml
package VotacionNocturna {

    class VotacionNocturna {
        - votos : Collection<Voto>
        + votaciones() : Collection<Voto>
        + resultadoVotacion() : Jugador
    }
    VotacionNocturna ---> Voto

}