!include estilos.puml
!include eleccion.puml
package VotacionNocturna {

    class VotacionNocturna {
        - votos : Collection<Eleccion>
        + registrarVoto(Eleccion)
        + resultadoVotacion() : Jugador
    }

    class Conteo {
        + sumarVotoPara(Jugador)
        + masVotado() : Jugador
    }

    VotacionNocturna --> Eleccion
    VotacionNocturna ..> Conteo

}
