ignore:
  - "src/main/java/edu/fiuba/paradigmas/controlador"
  - "src/main/java/edu/fiuba/paradigmas/vistas"
  - "src/main/java/edu/fiuba/paradigmas/App.java"
  - "src/main/java/edu/fiuba/paradigmas/Main.java"
  - "src/main/java/edu/fiuba/paradigmas/SystemInfo.java"
