@startuml
skinparam classAttributeIconSize 0
hide footbox

title Diagrama de secuencia fase nocturna completa - se protege a una victima

actor "Moderador" as mod

' participant ":EstadoPartida" as estado
' mod -> estado ** : <<create>> EstadoPartida([mica, sonny, cami, franco, rodrigo, maria, juan])


' participant ":FaseApertura" as fa
' mod -> fa ** : <<create>> FaseApertura()
' mod -> fa : ejecutar(jugadoresMafiosos)
' activate fa

participant ":FaseNocturna" as fn
participant ":VotacionNocturna" as vn

participant ":Jugador" as j
participant "carta:Rol" as carta

'participant "mafioso1:Jugador" as mafioso1
participant "carta1:Mafioso" as carta1

'participant "mafioso2:Jugador" as mafioso2
participant "carta2:Mafioso" as carta2

' fa -> mafioso1 : registrarComplices([mafioso2])
' fa -> mafioso2 : registrarComplices([mafioso1])

' deactivate fa


participant ":ResultadoNocturno" as resultado

'participant "detective:Jugador" as cami
participant "cartaD:Detective" as cartaD
participant "investigado:Jugador" as maria
participant "cartaI:Ciudadano" as cartaI
participant ":ResultadoInvestigacion" as ResultadoInvestigacion
'participant "medico:Jugador" as franco
participant "cartaM:Medico" as cartaF

' participant ":HistorialPartida" as h
' participant ":CondicionDeVictoria" as cdv

mod -> fn ** : <<create>> FaseNocturna()
mod -> fn : ejecutar(jugadoresVivos)

activate fn

    loop para cada jugador en jugadoresVivos
    fn -> j : c = getCarta()
    activate j
    j --> fn : carta
    deactivate j

    fn -> carta : aceptar(this)
    activate carta
    carta -> fn : visitar(this)
    activate fn
    fn -> fn : guardar(c)
    deactivate fn
    deactivate carta
    end

    fn -> vn ** : <<create>> VotacionNocturna()
    fn -> carta1 : elegirVictima(jugadoresVivos)
    activate carta1
    carta1 --> fn : juan
    deactivate carta1
    fn -> vn : registrarVoto(carta1, juan)
    fn -> carta2 : elegirVictima(jugadoresVivos)
    activate carta2
    carta2 --> fn : juan
    deactivate carta2
    fn -> vn : registrarVoto(carta2, juan)

    fn -> vn : resolverVictima()
    activate vn
    vn --> fn : juan
    deactivate vn


    fn -> cartaD : investigar(jugadoresVivos)
    activate cartaD
    
    cartaD -> maria : cI = getCarta()
    activate maria
    maria --> cartaD : cartaI
    deactivate maria

    cartaD -> cartaI : bandoAparente()
    activate cartaI
    
    cartaI --> cartaD : CIUDADANOS
    deactivate cartaI

    cartaD -> ResultadoInvestigacion ** : <<create>> ResultadoInvestigacion(maria, CIUDADANOS)    
    cartaD --> fn : resultadoInvestigacion
    deactivate cartaD


    fn -> cartaF : proteger(jugadoresVivos)
    activate cartaF
    cartaF --> fn : juan
    deactivate cartaF

''''''''''''''''''''''''''''''''''''''''''''''''''''
    fn -> resultado ** : <<create>> ResultadoNocturno(victima: juan, investigación: resultadoInvestigacion, protegido: juan)
    fn -> resultado : resolverResultado()
    activate resultado
    resultado --> fn : ResultadoNocturno
    deactivate resultado
    
    fn --> mod : ResultadoNocturno

deactivate fn

' mod -> estado : registrarResultado(ResultadoNocturno)
' mod -> h : registrarResultado(ResultadoNocturno)

' mod -> resultado : getEliminado()
' activate resultado
' resultado --> mod : juan
' deactivate resultado

' mod -> estado : eliminarJugador(juan)

' mod -> cdv : verificarCondicion(estado)

' cdv --> mod : No se cumple la condición de victoria




@enduml